### ISSUE TITLE
Make game data not encrypted

### ISSUE THREAD

**Issue by e-minguez** [hirak99/steam_deck_encryption#2]
While ideally everything must be encrypted, game data can earn some performance if they are not encrypted. Maybe maintaining a symlink on the proper .local data folder to the non crypted folder....

**Comment by hirak99** [comment]
LUKS is quite fast to notice any delay on most games (I see ~2G / s encryption/decryption speed with `cryptsetup benchmark`).

But may be it can speed up loading textures for some really heavy games? Would be worth checking to see if we indeed see any difference (my guess is that it would be imperceptible but I'm happy to be proven wrong).

If you want to try it, I suggest letting steam manage it by adding a path to an unencrypted location in Steam's storage settings (i.e. Option 2).

**Option 1: Symlink ourselves**

This involves moving and symlinking `/home/deck/.local/share/Steam/steamapps` somewhere, e.g. into `/home/_unencrypted_steamapps`.

I am fairly sure Steam should work fine with this.

**Option 2: Add unencrypted directory to Steam storage settings**

This may be simpler and safer. Create a common directory -

```sh
sudo mkdir /home/_unencrypted_games
sudo chown deck:deck /home/_unencrypted_games
```

And just add it to Settings --> Storage from the Steam UI.

This will allow Steam to fully manage the directory, and also allow us to choose destinations of games.

**Comment by e-minguez** [comment]
I don't have any numbers and I've read opinions on both fronts (see https://scs.community/2023/02/24/impact-of-disk-encryption/ for a recent one).
I'll try to find time to try your second approach as it seems easier.
Thanks.

**Comment by hirak99** [comment]
SG. Let me know if you run into any issues.

**Comment by e-minguez** [comment]
Creating a new library works like a charm. The only detail is that the shader cache and compdata is still stored in the encrypted container but it can be solved with a couple of symlinks.
Thanks!

**Comment by hirak99** [comment]
You're welcome. Resolving.
