### ISSUE TITLE
Decky doesn't seem to work 

### ISSUE THREAD

**Issue by e-minguez** [hirak99/steam_deck_encryption#9]
Installing decky on the "encrypted user" doesn't seem to work. It seems it installs a systemd unit that probably fails after the reboot (I couldn't troubleshoot it honestly)

**Comment by hirak99** [comment]
Create a `/home/deck/on_decrypt_root.sh` (on the encrypted directory, i.e. you can do it after you unlocked) with this content -

```sh
#!/bin/bash

# This is run when the home directory is decrypted.

set -uexo pipefail

# Decky loader service.
if [[ -f /etc/systemd/system/plugin_loader.service ]]; then
  systemctl start plugin_loader
fi
```

Change ownership to root and make it readonly for safety -

```sh
sudo chown root:root /home/deck/on_decrypt_root.sh
sudo chmod 744 /home/deck/on_decrypt_root.sh
```

Then from the next boot it should work.

I use decky myself! I will add these instructions to the repo.

**Comment by hirak99** [comment]
Hi Eduardo, did it work?

**Comment by e-minguez** [comment]
It did indeed!

**Comment by hirak99** [comment]
Glad to hear it!

Added to the instructions, resolving this then.
